[default]
address = "127.0.0.1"
limits = { forms = "64 kB", json = "100 MiB" }
port = 8000

database_url = "sqlite:database.sqlite" 
process_directory = "./processes"
hypervisor_socket_path = "/tmp/simple-scheduler.sock"
private_key_path = "./test-data/authentification/private.rsa.pkcs8.der"
public_key_path = "./test-data/authentification/public.rsa.pkcs8.der"

## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 8800
secret_key = "O/9ToubKlU0ad+isM3DxIvHV47Td40IjVaVYEDYtdqE="
