[build]
# we need `uuid_unstable` to generate UUID v7,
# which are more suited for use as primary keys in databases.
rustflags = [
    "--cfg",
    "uuid_unstable"
]

# we can't target `x86_64-unknown-linux-musl`,
# to have an entirely statically linked library
# until the `ring` dependendy supports it
# see: https://github.com/briansmith/ring/issues/713
# target = "x86_64-unknown-linux-musl"
